Use Python venv for coverage too

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -10,6 +10,7 @@ on:
   workflow_dispatch:
 
 env:
+  DEFAULT_PYTHON: "3.13"
   PRE_COMMIT_CACHE: ~/.cache/pre-commit
 
 concurrency:
@@ -314,23 +315,35 @@ jobs:
   coverage:
     name: Process test coverage
     runs-on: ubuntu-latest
-    needs: ["pytest"]
+    needs: ["pytest", "prepare"]
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v4.2.2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v5.6.0
+        id: python
         with:
-          fetch-depth: 0
-      - name: Download coverage data
-        uses: actions/download-artifact@v4.1.8
-      - name: Set up uv
-        uses: astral-sh/setup-uv@v6.4.3
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v4.2.3
         with:
-          enable-cache: true
-      - name: Install dependencies
-        run: uv sync --frozen --dev
-      - name: Process coverage results
+          path: venv
+          key: >
+            ${{ runner.os }}-venv-${{ env.DEFAULT_PYTHON }}-
+            ${{ hashFiles('pyproject.toml') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
-          uv run --frozen coverage combine coverage*/.coverage*
-          uv run --frozen coverage xml -i
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Download all coverage artifacts
+        uses: actions/download-artifact@v5.0.0
+      - name: Combine coverage results
+        run: |
+          . venv/bin/activate
+          coverage combine coverage*/.coverage*
+          coverage report
+          coverage xml
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v5.4.3
